---
downloads: ~/.ansible-downloads/

# add .idea to gitignore
configure_dotfiles: true
configure_terminal: true
configure_osx: true

# Set to 'true' to configure the Dock via dockutil.
configure_dock: false
dockitems_remove: []
# - Launchpad
# - TV
# - Podcasts
# - 'App Store'
dockitems_persist: []
# - name: "Sublime Text"
#   path: "/Applications/Sublime Text.app/"
#   pos: 5

configure_sudoers: false
sudoers_custom_config: ''
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

dotfiles_repo: https://github.com/geerlingguy/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/Development/GitHub/dotfiles
dotfiles_files:
  - .zshrc
  - .gitignore
  - .inputrc
  - .osx
  - .vimrc

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - bash-completion
  - git
  - github/gh/gh
  - node
  - nvm
  - wget
  - zsh-history-substring-search
  - jenv
  - maven

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - adoptopenjdk/openjdk
#  echo 'eval "$(jenv init -)"' >> ~/.zprofile
#  source ~/.zprofile
#  jenv add /Library/Java/JavaVirtualMachines/adoptopenjdk-{whatever_version_was_installed}.jdk/Contents/Home/
#  jenv global openjdk64-1.8.0.{whatever_build_was_installed}
#  echo 'export PATH="$HOME/.jenv/bin:$PATH"' > ~/.zprofile
#  echo 'eval "$(jenv init -)"' >> ~/.zprofile
#  jenv enable-plugin maven

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - google-chrome
  - sequel-ace
  - slack
  - sublime-text
  - adoptopenjdk8
  - intellij-idea
  - postman

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Set to 'true' to configure Sublime Text.
configure_sublime: false
sublime_base_path: '~/Library/Application Support/Sublime Text'
sublime_config_path: "Packages/User"
sublime_package_control:
  - "DocBlockr"
  - "Dockerfile Syntax Highlighting"
  - "FileDiffs"
  - "GitHub Flavored Markdown Preview"
  - "Jinja2"
  - "Package Control"
  - "PHP-Twig"
  - "Pretty JSON"
  - "SublimeLinter"
  - "SublimeLinter-contrib-yamllint"
  - "TrailingSpaces"
  - "WordCount"

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
